=== seanttaylor/hypertoast/schemas/link-relation.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "http://com.hypertoast/schemas/link-relation.json",
    "type": "object",
    "default": {},
    "title": "The Link Relation Schema",
    "required": [
        "title",
        "name",
        "description"
    ],
    "properties": {
        "title": {
            "type": "string",
            "default": "",
            "title": "The title Schema",
            "examples": [
                "Device Settings"
            ]
        },
        "name": {
            "type": "string",
            "default": "",
            "title": "The name Schema",
            "examples": [
                "settings"
            ]
        },
        "description": {
            "type": "string",
            "default": "",
            "title": "The description Schema",
            "examples": [
                "The 'settings' link relation is used to provide web clients with the ability to adjust the settings of the smart toaster and to customize the functionality of the toaster to better suit their needs and preferences. Clients may adjust various settings, such as the toasting time, the level of toasting, and the type of bread that is being toasted."
            ]
        },
        "method": {
            "type": "string",
            "default": "",
            "title": "The method Schema",
            "examples": [
                "PUT"
            ]
        },
        "schema": {
            "type": "object",
            "default": {},
            "title": "The schema Schema",
            "required": [
                "href"
            ],
            "properties": {
                "href": {
                    "type": "string",
                    "default": "",
                    "title": "The href Schema",
                    "examples": [
                        "/schemas/v1/settings"
                    ]
                }
            },
            "examples": [{
                "href": "/schemas/v1/settings"
            }]
        },
        "tags": {
            "type": "object",
            "default": {},
            "title": "The tags Schema",
            "required": [
                "href"
            ],
            "properties": {
                "href": {
                    "type": "string",
                    "default": "",
                    "title": "The href Schema",
                    "examples": [
                        "/tags/settings/{version}"
                    ]
                },
                "templated": {
                    "type": "boolean",
                    "default": false,
                    "title": "The templated Schema",
                    "examples": [
                        true
                    ]
                }
            },
            "examples": [{
                "href": "/tags/settings/{version}",
                "templated": true
            }]
        },
        "headers": {
            "type": "object",
            "default": {},
            "title": "The headers Schema",
            "required": [
                
            ],
            "properties": {
                "accept": {
                    "type": "array",
                    "default": [],
                    "title": "The accept Schema",
                    "items": {
                        "type": "string",
                        "title": "A Schema",
                        "examples": [
                            "application/vnd.hypertoast",
                            "schema=http://localhost:3010/schemas/settings"
                        ]
                    },
                    "examples": [
                        ["application/vnd.hypertoast",
                            "schema=http://localhost:3010/schemas/settings"
                        ]
                    ]
                }
            },
            "examples": [{
                "accept": [
                    "application/vnd.hypertoast",
                    "schema=http://localhost:3010/schemas/settings"
                ]
            }]
        }
    },
    "examples": [{
        "title": "Device Settings",
        "name": "settings",
        "description": "The 'settings' link relation is used to provide web clients with the ability to adjust the settings of the smart toaster and to customize the functionality of the toaster to better suit their needs and preferences. Clients may adjust various settings, such as the toasting time, the level of toasting, and the type of bread that is being toasted.",
        "method": "PUT",
        "schema": {
            "href": "/schemas/v1/settings"
        },
        "tags": {
            "href": "/tags/settings/{version}",
            "templated": true
        },
        "headers": {
            "accept": [
                "application/vnd.hypertoast",
                "schema=http://localhost:3010/schemas/settings"
            ]
        }
    }]
}

=== seanttaylor/hypertoast/relations/status.json
{   
    "title": "Device Status",
    "name": "status",
    "description": "The 'status' link relation is used to provide web clients with real-time updates on the current status of the smart toaster, as well as device information related to the toaster. This link relation enable clients to monitor the operation of the toaster and view relevant information about its configuration and performance. Exampes include whether it is currently toasting bread or is idle, as well as device information such as the firmware version, network connectivity status, and other technical details.",
    "headers": {
        "accept": [
            "application/vnd.hypertoast"
        ],
        "content-type": "application/json"
    }
}

=== seanttaylor/hypertoast/relations/off.json
{   
    "title": "The Off State",
    "name": "of",
    "description": "The 'off' link relation is used to indicate the deactivation of the smart toaster. When a client deactivates the toaster, it enters an 'off' state, indicating that it is no longer ready to toast bread or other items. Following this link relation, it triggers the deactivation of the toaster and set it to the appropriate state for storing or cleaning.",
    "method": "PUT"
}
